version: "3"
services:
  db:
    image: "postgres:11"
    container_name: "petrie_db"
    ports:
      - "5432:5432"
    volumes:
      - ./conf/evolutions/default/schema.sql:/docker-entrypoint-initdb.d/init.sql
